rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [joint1]
    gains:
      joint1: {p: 100.0, i: 0.05, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [joint2]
    gains:
      joint2: {p: 100.0, i: 0.05, d: 10.0}