servo:
    # Publish all joint states -----------------------------------
    joints_update:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # Position Controllers ---------------------------------------
    junta_position_controller:
      type: position_controllers/JointPositionController
      joint: junta
      pid: {p: 1, i: 0, d: 1, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}
    
    # Position Controllers ---------------------------------------
    junta_trajectory_controller:
      type: position_controllers/JointTrajectoryController
      joints: 
        - junta
      pid: {p: 1, i: 0, d: 1, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

controller_list:
  - name: /servo/junta_trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["junta"]