scara:
    # Publish all joint states -----------------------------------
    joints_update:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    
    # articulacion Controllers ---------------------------------------
    articulacion_position_controller:
      type: velocity_controllers/JointPositionController
      joint: articulacion
      pid: {p: 100, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

    articulacion_trajectory_controller:
      type: velocity_controllers/JointTrajectoryController
      joints: [articulacion]
      gains:
        articulacion: {p: 100, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

    # muneca Controllers ---------------------------------------
    muneca_position_controller:
      type: velocity_controllers/JointPositionController
      joint: muneca
      pid: {p: 1, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

    muneca_trajectory_controller:
      type: velocity_controllers/JointTrajectoryController
      joints: [muneca]
      gains:
        muneca: {p: 1, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

    # codo Controllers ---------------------------------------
    codo_position_controller:
      type: velocity_controllers/JointPositionController
      joint: codo
      pid: {p: 1, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

    codo_trajectory_controller:
      type: velocity_controllers/JointTrajectoryController
      joints: [codo]
      gains:
        codo: {p: 10, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}    

    # hombro Controllers ---------------------------------------
    hombro_position_controller:
      type: velocity_controllers/JointPositionController
      joint: hombro
      pid: {p: 10, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

    hombro_trajectory_controller:
      type: velocity_controllers/JointTrajectoryController
      joints: [hombro]
      gains:
        hombro: {p: 10, i: 0, d: 0, i_clamp_min: -130.0, i_clamp_max: 130, antiwindup: True}

controller_list:
  - name: /scara/articulacion_trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["articulacion"]
  - name: /scara/muneca_trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["muneca"]       
  - name: /scara/codo_trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["codo"] 
  - name: /scara/hombro_trajectory_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["hombro"]        