scara:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [Joint1]
    gains:
      Joint1: {p: 100.0, i: 0.05, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [Joint2]
    gains:
      Joint2: {p: 100.0, i: 0.05, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [Joint3]
    gains:
      Joint3: {p: 100.0, i: 0.05, d: 10.0}

controller_list:
  - name: /scara/joint1_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["Joint1"]
  - name: /scara/joint2_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["Joint2"]
  - name: /scara/joint3_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["Joint3"]