controller_list:
  - name: /scara/hombro_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["hombro"]
  - name: /scara/codo_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["codo"]
  - name: /scara/muneca_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["muneca"]
  - name: /scara/articulacion_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["articulacion"]