servo:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  junta_position_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [junta]
    gains:
      junta: {p: 100.0, i: 0.05, d: 10.0}

controller_list:
  - name: /servo/junta_position_controller
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: ["junta"]